-- Rôle du contact dans le suivi de candidature.
--
-- Le formulaire de contact des maquettes (SPECDESIGN/Modales.dc.html) porte un champ
-- « Rôle dans le suivi » — recruteur, manager, référent — que la table ne connaissait pas.
-- SPECDESIGN étant prioritaire pour l'interface (MIGRATION.md §34), la colonne est ajoutée
-- plutôt que le champ retiré.
--
-- Nullable et sans valeur par défaut : les contacts déjà saisis n'ont pas de rôle, et en
-- inventer un serait une donnée fausse. L'interface affiche « Non renseigné ».
--
-- Pas de contrainte CHECK, contrairement aux enums de `candidatures` et `entretiens` : le
-- rôle est un texte libre dans les maquettes, et figer une liste ici obligerait à une
-- migration à chaque rôle que l'utilisateur voudrait nommer autrement.
ALTER TABLE contacts ADD COLUMN role_suivi TEXT;
