import { useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import type { Profil } from "@/shared/types/generated/profil";
import { iaService, generationId } from "@/features/ia/services/ia.service";
import { useIaProgress } from "@/features/ia/viewmodel/useIaProgress";
import { IaProgress } from "@/features/documents/view/components/DocumentUi";
import { AppError } from "@/shared/types/app-error";
import { Button, ErrorBanner, Icon, ModalHost } from "@/shared/ui";

/** Import PDF avec aperçu explicite avant fusion dans le profil existant. */
export function ProfilImportModal({ open: visible, profil, busy, onClose, onSubmit }: { open: boolean; profil: Profil; busy: boolean; onClose: () => void; onSubmit: (profil: Profil) => Promise<unknown> }) {
  const [path, setPath] = useState<string | null>(null); const [operation, setOperation] = useState<string | null>(null); const [extrait, setExtrait] = useState<Profil | null>(null); const [error, setError] = useState<string | null>(null); const progress = useIaProgress(operation);
  const choisir = async () => { const file = await open({ multiple:false, filters:[{ name:"PDF", extensions:["pdf"] }] }); if (typeof file !== "string") return; setPath(file); setExtrait(null); setError(null); };
  const analyser = async () => { if (!path) return; const id = generationId(); setOperation(id); setError(null); try { setExtrait((await iaService.importerProfil({ generationId:id, chemin:path })).profil); } catch(e) { if (!(e instanceof AppError && e.code === "CANCELLED")) setError(e instanceof AppError ? e.message : "Le CV n’a pas pu être analysé."); } finally { setOperation(null); } };
  const appliquer = async () => { if (!extrait) return; await onSubmit(fusionnerProfil(profil, extrait)); onClose(); };
  return <ModalHost open={visible} icon="upload_file" title="Importer depuis un CV" subtitle="L’IA prépare les données ; vous gardez le dernier mot" submitLabel="Ajouter au profil" submitIcon="playlist_add_check" submitDisabled={!extrait} busy={busy} onClose={onClose} onSubmit={() => void appliquer()} width="720px"><div className="space-y-4"><button type="button" onClick={() => void choisir()} className="flex w-full flex-col items-center gap-2 rounded-card border border-dashed border-accent-border bg-accent-tint px-6 py-7 text-center"><Icon name={path ? "picture_as_pdf" : "upload_file"} size={28} className="text-accent" /><span className="font-medium text-ink">{path ? path.split("/").at(-1) : "Choisir un CV PDF"}</span><span className="text-meta text-ink-muted">Lecture locale · 10 Mo maximum</span></button>{path && !extrait && !operation ? <Button variant="primary" icon="auto_awesome" className="w-full" onClick={() => void analyser()}>Analyser et préparer les données</Button> : null}{operation ? <><IaProgress progress={progress} /><Button variant="danger" icon="stop" className="w-full" onClick={() => void iaService.annuler(operation)}>Annuler l’analyse</Button></> : null}{error ? <ErrorBanner title="Import impossible" message={error} /> : null}{extrait ? <div className="rounded-card border border-line bg-surface-alt p-4"><div className="flex items-center gap-2"><Icon name="check_circle" size={18} className="text-success" /><p className="font-medium text-ink">Données prêtes à être ajoutées</p></div><p className="mt-2 text-body text-ink-muted">{[extrait.identite.prenom, extrait.identite.nom].filter(Boolean).join(" ") || "Identité non détectée"}</p><dl className="mt-4 grid grid-cols-3 gap-3 text-center"><Count label="Expériences" value={extrait.experiences.length} /><Count label="Compétences" value={extrait.competences.length} /><Count label="Formations" value={extrait.formations.length} /><Count label="Langues" value={extrait.langues.length} /><Count label="Projets" value={extrait.projets.length} /><Count label="Certifications" value={extrait.certifications.length} /></dl><p className="mt-4 text-meta leading-relaxed text-ink-faint">Les nouvelles entrées seront fusionnées avec votre profil. Les doublons exacts sont ignorés.</p></div> : null}</div></ModalHost>;
}

function Count({ label, value }: { label:string; value:number }) { return <div className="rounded-field bg-surface p-2"><dt className="text-[10px] text-ink-faint">{label}</dt><dd className="tabular mt-1 font-semibold text-ink">{value}</dd></div>; }

export function fusionnerProfil(actuel: Profil, importe: Profil): Profil {
  const texte = (nouveau: string | null, ancien: string | null) => nouveau?.trim() ? nouveau : ancien;
  const fusion = <T,>(a: T[], b: T[], key: (item:T) => string): T[] => { const vus = new Set(a.map((item) => key(item).trim().toLowerCase())); return [...a, ...b.filter((item) => { const k = key(item).trim().toLowerCase(); if (!k || vus.has(k)) return false; vus.add(k); return true; })]; };
  return { identite:{ prenom:texte(importe.identite.prenom, actuel.identite.prenom) ?? "", nom:texte(importe.identite.nom, actuel.identite.nom) ?? "", email:texte(importe.identite.email, actuel.identite.email) ?? "", telephone:texte(importe.identite.telephone, actuel.identite.telephone), ville:texte(importe.identite.ville, actuel.identite.ville), titre:texte(importe.identite.titre, actuel.identite.titre), resume:texte(importe.identite.resume, actuel.identite.resume), linkedin:texte(importe.identite.linkedin, actuel.identite.linkedin), github:texte(importe.identite.github, actuel.identite.github), siteWeb:texte(importe.identite.siteWeb, actuel.identite.siteWeb) }, experiences:fusion(actuel.experiences, importe.experiences, (v) => `${v.intitule}|${v.entreprise}|${v.dateDebut}`), competences:fusion(actuel.competences, importe.competences, (v) => v.nom), formations:fusion(actuel.formations, importe.formations, (v) => `${v.diplome}|${v.etablissement}`), langues:fusion(actuel.langues, importe.langues, (v) => v.nom), projets:fusion(actuel.projets, importe.projets, (v) => v.nom), certifications:fusion(actuel.certifications, importe.certifications, (v) => v.nom) };
}
