//! Helpers communs et déclaration des cas de test.
use super::*;

mod test_connexion_du_pool_active_les_cles_etrangeres;
mod test_migration_metier_cree_toutes_les_tables;
mod test_migrations_base_heritee_ne_rejoue_pas_les_versions_deja_appliquees;
mod test_migrations_base_heritee_version_zero_purge_et_supprime_les_tables_retirees;
mod test_migrations_base_neuve_applique_toutes_les_versions;
mod test_migrations_executees_deux_fois_restent_idempotentes;
mod test_migrations_sont_declarees_dans_un_ordre_strictement_croissant;
mod test_open_pool_memoire_partage_les_donnees_entre_connexions;
mod test_suppression_candidature_efface_ses_relances_en_cascade;
mod test_suppression_entreprise_referencee_est_refusee;
mod test_table_parametres_refuse_une_seconde_ligne;
