import { useState } from "react";
import { open, save } from "@tauri-apps/plugin-dialog";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { documentsService } from "../../services/documents.service";
import type { CvVersion, Lettre } from "../../services/documents.service";
import { iaService, generationId } from "@/features/ia/services/ia.service";
import type { AnalyseCvImporte, CvGenere, GenerationCv } from "@/features/ia/model/types";
import { useIaProgress } from "@/features/ia/viewmodel/useIaProgress";
import { useUiStore } from "@/shared/lib/ui-store";
import type { ToastMessage } from "@/shared/lib/ui-store";
import { AppError } from "@/shared/types/app-error";
import { Button, ConfirmDialog, EmptyState, ErrorBanner, FormField, Icon, PageHeader, Select, TextArea, TextInput } from "@/shared/ui";
import { A4Preview, DocumentPanel, IaProgress, ScoreBadge } from "../components/DocumentUi";

const CV_KEY = ["documents", "cv"] as const;
const LETTRES_KEY = ["documents", "lettres"] as const;

export function CvLibraryPage() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const notify = useUiStore((s) => s.notify);
  const list = useQuery({ queryKey: CV_KEY, queryFn: documentsService.listerCv });
  const [selected, setSelected] = useState<string | null>(null); const [deleteId, setDeleteId] = useState<string | null>(null); const selectedId = selected ?? list.data?.[0]?.id ?? null;
  const detail = useQuery({ queryKey: [...CV_KEY, selectedId], queryFn: () => documentsService.obtenirCv(selectedId ?? ""), enabled: selectedId !== null });
  const remove = useMutation({ mutationFn: documentsService.supprimerCv, onSuccess: async () => { setSelected(null); setDeleteId(null); await queryClient.invalidateQueries({ queryKey: CV_KEY }); notify({ tone: "success", title: "Version supprimée" }); } });
  return <Screen header={<PageHeader icon="description" title="Mes CV" subtitle={list.data ? `${list.data.length} version${list.data.length > 1 ? "s" : ""} prête${list.data.length > 1 ? "s" : ""} à l’emploi` : "Vos versions prêtes à l’emploi"} primary={<Button variant="primary" icon="auto_awesome" onClick={() => void navigate("/documents/generer-cv")}>Nouveau CV</Button>} />}>
    {list.error ? <ErrorBanner message={message(list.error)} onRetry={() => void list.refetch()} /> : <div className="grid min-h-[620px] gap-4 xl:grid-cols-[minmax(340px,0.75fr)_minmax(480px,1.25fr)]"><DocumentPanel title="Bibliothèque personnelle" icon="folder_open"><div className="p-3">{list.isLoading ? <p className="p-6 text-center text-ink-muted">Chargement…</p> : list.data?.length ? <ul className="grid gap-3 sm:grid-cols-2 xl:grid-cols-2">{list.data.map((cv) => <li key={cv.id}><button type="button" aria-pressed={selected === cv.id} onClick={() => setSelected(cv.id)} className={`w-full overflow-hidden rounded-card border text-left transition-colors ${selected === cv.id ? "border-accent bg-accent-tint" : "border-line bg-surface-alt hover:border-accent-border"}`}><div className="mx-3 mt-3 h-36 bg-white p-4 shadow-e1"><span className="block h-2 w-2/3 bg-[#5b6ee1]/25" /><span className="mt-4 block h-1.5 w-full bg-[#dfe3eb]" /><span className="mt-2 block h-1.5 w-4/5 bg-[#dfe3eb]" /></div><div className="p-3"><p className="truncate font-medium text-ink">{cv.nom}</p><p className="mt-1 text-meta text-ink-faint">{date(cv.createdAt)}</p></div></button></li>)}</ul> : <EmptyState icon="description" title="Aucune version" description="Générez puis sauvegardez votre premier CV ciblé." action={<Button icon="auto_awesome" onClick={() => void navigate("/documents/generer-cv")}>Générer un CV</Button>} />}</div></DocumentPanel><DocumentPanel title={detail.data?.nom ?? "Aperçu"} icon="visibility" action={detail.data ? <div className="flex gap-2">{isGeneration(detail.data.contenu) ? <Button icon="download" onClick={() => { const generation = detail.data?.contenu; if (detail.data && isGeneration(generation)) void exporterPdf(generation.cv, detail.data.nom, notify); }}>Exporter PDF</Button> : null}<Button variant="danger" icon="delete" onClick={() => setDeleteId(detail.data?.id ?? null)}>Supprimer</Button></div> : null}>{detail.data ? <CvSavedPreview version={detail.data} /> : <EmptyState icon="visibility" title="Sélectionnez une version" description="Son contenu détaillé apparaîtra ici." />}</DocumentPanel></div>}
    <ConfirmDialog open={deleteId !== null} title="Supprimer cette version ?" description="Le CV disparaîtra définitivement de la bibliothèque locale." note="Votre profil et vos autres versions seront conservés." busy={remove.isPending} onCancel={() => setDeleteId(null)} onConfirm={() => { if (deleteId) remove.mutate(deleteId); }} />
  </Screen>;
}

function CvSavedPreview({ version }: { version: CvVersion }) { const generation = isGeneration(version.contenu) ? version.contenu : null; return generation ? <A4Preview cv={generation.cv} /> : <A4Preview title={version.nom}><div className="flex min-h-[590px] items-center justify-center text-center text-[#7b8493]">Cette ancienne version ne contient pas encore d’aperçu structuré compatible.</div></A4Preview>; }

export function CvGeneratorPage() {
  const queryClient = useQueryClient(); const notify = useUiStore((s) => s.notify); const [offre, setOffre] = useState(""); const [operation, setOperation] = useState<string | null>(null); const [result, setResult] = useState<GenerationCv | null>(null); const [error, setError] = useState<string | null>(null); const [nom, setNom] = useState(""); const progress = useIaProgress(operation);
  const run = async () => { if (!offre.trim()) { setError("Collez le texte de l’offre à cibler."); return; } const id = generationId(); setOperation(id); setError(null); try { const value = await iaService.genererCv({ generationId: id, offre }); setResult(value); setNom(`CV — ${value.offre.titre || "Version ciblée"}`); } catch (e) { if (!(e instanceof AppError && e.code === "CANCELLED")) setError(message(e)); } finally { setOperation(null); } };
  const save = useMutation({ mutationFn: () => documentsService.enregistrerCv({ nom, contenu: result }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: CV_KEY }); notify({ tone: "success", title: "CV ajouté à la bibliothèque" }); } });
  return <Screen header={<PageHeader icon="auto_awesome" title="Générer un CV" subtitle="Analysez une offre, adaptez votre profil, mesurez le score ATS" secondary={result ? <Button icon="download" onClick={() => void exporterPdf(result.cv, nom || "cv-candilog", notify)}>Exporter PDF</Button> : undefined} primary={result ? <Button variant="primary" icon="save" disabled={!nom.trim() || save.isPending} onClick={() => save.mutate()}>Enregistrer</Button> : undefined} />}>
    <div className="grid min-h-[660px] gap-4 xl:grid-cols-[350px_minmax(460px,1fr)_320px]"><DocumentPanel title="Offre ciblée" icon="target"><div className="space-y-4 p-4"><FormField label="Texte de l’offre" required help="Le texte est envoyé uniquement au fournisseur configuré.">{(props) => <TextArea {...props} rows={18} value={offre} placeholder="Collez ici l’intitulé, les missions et les compétences recherchées…" onChange={(e) => setOffre(e.target.value)} />}</FormField>{error ? <ErrorBanner title="Génération impossible" message={error} /> : null}{operation ? <><IaProgress progress={progress} /><Button variant="danger" icon="stop" className="w-full" onClick={() => void iaService.annuler(operation)}>Annuler</Button></> : <Button variant="primary" icon="auto_awesome" className="w-full" onClick={() => void run()}>Générer le CV ciblé</Button>}</div></DocumentPanel><DocumentPanel title="Aperçu HTML · A4" icon="article"><A4Preview cv={result?.cv} /></DocumentPanel><DocumentPanel title="Analyse ATS" icon="query_stats"><div className="space-y-5 p-4">{result ? <><ScoreBadge value={result.analyse.score} /><p className="text-body leading-relaxed text-ink-muted">{result.analyse.recap}</p><div><p className="mb-2 text-label font-medium text-ink">Suggestions</p><ul className="space-y-2">{result.analyse.suggestions.map((s, i) => <li key={i} className="flex gap-2 text-body text-ink-muted"><Icon name="arrow_right" size={15} className="mt-0.5 text-accent" />{s}</li>)}</ul></div><FormField label="Nom de la version" required>{(props) => <TextInput {...props} value={nom} onChange={(e) => setNom(e.target.value)} />}</FormField></> : <EmptyState icon="query_stats" title="Analyse en attente" description="Le score et les recommandations suivront la génération." />}</div></DocumentPanel></div>
  </Screen>;
}

export function LettersLibraryPage() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [selected, setSelected] = useState<string | null>(null); const [deleteId, setDeleteId] = useState<string | null>(null); const list = useQuery({ queryKey: LETTRES_KEY, queryFn: documentsService.listerLettres }); const selectedId = selected ?? list.data?.[0]?.id ?? null; const selectedLetter = list.data?.find((l) => l.id === selectedId) ?? null; const remove = useMutation({ mutationFn: documentsService.supprimerLettre, onSuccess: async () => { setSelected(null); setDeleteId(null); await queryClient.invalidateQueries({ queryKey: LETTRES_KEY }); } });
  return <Screen header={<PageHeader icon="mail" title="Mes lettres de motivation" subtitle={list.data ? `${list.data.length} lettre${list.data.length > 1 ? "s" : ""} dans votre bibliothèque` : "Votre bibliothèque de lettres"} primary={<Button variant="primary" icon="auto_awesome" onClick={() => void navigate("/documents/rediger-lettre")}>Rédiger une lettre</Button>} />}>
    {list.error ? <ErrorBanner message={message(list.error)} onRetry={() => void list.refetch()} /> : <div className="grid min-h-[620px] gap-4 xl:grid-cols-[360px_minmax(480px,1fr)]"><DocumentPanel title="Bibliothèque" icon="folder_open">{list.isLoading ? <p className="p-6 text-center text-ink-muted">Chargement…</p> : list.data?.length ? <ul className="divide-y divide-line">{list.data.map((letter) => <li key={letter.id}><button type="button" aria-pressed={selected === letter.id} onClick={() => setSelected(letter.id)} className={`w-full px-4 py-3 text-left ${selected === letter.id ? "bg-accent-tint" : "hover:bg-neutral-tint"}`}><p className="font-medium text-ink">{letter.nom}</p><p className="mt-1 truncate text-meta text-ink-muted">{letter.entreprise ?? "Entreprise"} · {date(letter.createdAt)}</p></button></li>)}</ul> : <EmptyState icon="mail" title="Aucune lettre enregistrée" description="Rédigez une lettre puis enregistrez-la ici." action={<Button icon="auto_awesome" onClick={() => void navigate("/documents/rediger-lettre")}>Rédiger une lettre</Button>} />}</DocumentPanel><DocumentPanel title={selectedLetter?.nom ?? "Lecture"} icon="draft" action={selectedLetter ? <Button variant="danger" icon="delete" onClick={() => setDeleteId(selectedLetter.id)}>Supprimer</Button> : null}>{selectedLetter ? <LetterPreview letter={selectedLetter} /> : <EmptyState icon="draft" title="Sélectionnez une lettre" />}</DocumentPanel></div>}
    <ConfirmDialog open={deleteId !== null} title="Supprimer cette lettre ?" description="La lettre sera retirée de la bibliothèque locale." note="Le profil et les autres documents seront conservés." busy={remove.isPending} onCancel={() => setDeleteId(null)} onConfirm={() => { if (deleteId) remove.mutate(deleteId); }} />
  </Screen>;
}

function LetterPreview({ letter }: { letter: Lettre }) { return <A4Preview title={letter.nom}><p className="mt-4 text-[11px] uppercase tracking-[0.12em] text-[#5b6ee1]">Lettre de motivation</p><h2 className="mt-3 text-[23px] font-semibold">{letter.poste ?? "Candidature"}</h2><p className="mt-1 text-[12px] text-[#6a7280]">{letter.entreprise ?? "Entreprise"}</p><div className="mt-8 whitespace-pre-wrap text-[12px] leading-[1.9]">{letter.contenu}</div></A4Preview>; }

export function LetterWriterPage() {
  const queryClient = useQueryClient(); const notify = useUiStore((s) => s.notify); const [entreprise, setEntreprise] = useState(""); const [poste, setPoste] = useState(""); const [ton, setTon] = useState("formal"); const [longueur, setLongueur] = useState("medium"); const [contexte, setContexte] = useState(""); const [output, setOutput] = useState(""); const [operation, setOperation] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const progress = useIaProgress(operation); const run = async () => { const id = generationId(); setOperation(id); setOutput(""); setError(null); try { setOutput(await iaService.genererLettre({ generationId:id, entreprise:entreprise || null, poste:poste || null, ton, longueur, contexte:contexte || null, lettrePrecedente:null, instruction:null })); } catch(e) { if (!(e instanceof AppError && e.code === "CANCELLED")) setError(message(e)); } finally { setOperation(null); } }; const save = useMutation({ mutationFn: () => documentsService.enregistrerLettre({ nom:`Lettre — ${poste || entreprise || "Candidature"}`, entreprise:entreprise || null, poste:poste || null, ton, longueur, contenu:output }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: LETTRES_KEY }); notify({ tone:"success", title:"Lettre enregistrée" }); } });
  return <Screen header={<PageHeader icon="edit_note" title="Lettre de motivation" subtitle="Brief, rédaction assistée et aperçu du document" primary={output ? <Button variant="primary" icon="save" disabled={save.isPending} onClick={() => save.mutate()}>Enregistrer</Button> : undefined} />}><div className="grid min-h-[660px] gap-4 xl:grid-cols-[350px_minmax(480px,1fr)]"><DocumentPanel title="Brief de rédaction" icon="target"><div className="space-y-4 p-4"><Champ label="Entreprise" value={entreprise} onChange={setEntreprise} /><Champ label="Poste ciblé" value={poste} onChange={setPoste} /><div className="grid grid-cols-2 gap-3"><FormField label="Ton">{(props) => <Select {...props} value={ton} onChange={(e) => setTon(e.target.value)}><option value="formal">Formel</option><option value="casual">Naturel</option><option value="creative">Créatif</option></Select>}</FormField><FormField label="Longueur">{(props) => <Select {...props} value={longueur} onChange={(e) => setLongueur(e.target.value)}><option value="short">Courte</option><option value="medium">Moyenne</option><option value="long">Longue</option></Select>}</FormField></div><FormField label="Contexte ou offre">{(props) => <TextArea {...props} rows={10} value={contexte} onChange={(e) => setContexte(e.target.value)} />}</FormField>{error ? <ErrorBanner title="Rédaction impossible" message={error} /> : null}{operation ? <><IaProgress progress={progress} /><Button variant="danger" icon="stop" className="w-full" onClick={() => void iaService.annuler(operation)}>Arrêter</Button></> : <Button variant="primary" icon="auto_awesome" className="w-full" onClick={() => void run()}>Rédiger la lettre</Button>}</div></DocumentPanel><DocumentPanel title="Document" icon="draft"><A4Preview title="Lettre de motivation"><p className="mt-4 text-[11px] uppercase tracking-[0.12em] text-[#5b6ee1]">Lettre de motivation</p><h2 className="mt-3 text-[23px] font-semibold">{poste || "Candidature"}</h2><p className="mt-1 text-[12px] text-[#6a7280]">{entreprise || "Entreprise ciblée"}</p><div className="mt-8 whitespace-pre-wrap text-[12px] leading-[1.9] text-[#303641]">{output || "La lettre apparaîtra ici après la rédaction."}</div></A4Preview></DocumentPanel></div></Screen>;
}

export function CvAnalysisPage() {
  const [path, setPath] = useState<string | null>(null); const [offre, setOffre] = useState(""); const [operation, setOperation] = useState<string | null>(null); const [result, setResult] = useState<AnalyseCvImporte | null>(null); const [error, setError] = useState<string | null>(null); const progress = useIaProgress(operation); const choose = async () => { const file = await open({ multiple:false, filters:[{ name:"PDF", extensions:["pdf"] }] }); if (typeof file === "string") setPath(file); }; const run = async () => { if (!path || !offre.trim()) { setError("Sélectionnez un PDF et collez l’offre ciblée."); return; } const id = generationId(); setOperation(id); setError(null); try { setResult(await iaService.analyserCv({ generationId:id, chemin:path, offre })); } catch(e) { if (!(e instanceof AppError && e.code === "CANCELLED")) setError(message(e)); } finally { setOperation(null); } };
  return <Screen header={<PageHeader icon="query_stats" title="Analyse de CV" subtitle="Comparez un PDF à l’offre ciblée — lecture du fichier en local" primary={<Button variant="primary" icon="bolt" disabled={operation !== null} onClick={() => void run()}>Analyser le CV</Button>} />}><div className="grid gap-4 xl:grid-cols-[400px_minmax(480px,1fr)]"><div className="space-y-4"><DocumentPanel title="Document à analyser" icon="upload_file"><div className="space-y-4 p-4"><button type="button" onClick={() => void choose()} className="flex w-full flex-col items-center gap-2 rounded-card border border-dashed border-accent-border bg-accent-tint px-5 py-8 text-center"><Icon name={path ? "picture_as_pdf" : "upload_file"} size={28} className="text-accent" /><span className="font-medium text-ink">{path ? path.split("/").at(-1) : "Choisir un CV PDF"}</span><span className="text-meta text-ink-muted">PDF uniquement · 10 Mo maximum</span></button><FormField label="Offre ciblée" required>{(props) => <TextArea {...props} rows={13} value={offre} onChange={(e) => setOffre(e.target.value)} />}</FormField>{operation ? <IaProgress progress={progress} /> : null}{error ? <ErrorBanner title="Analyse impossible" message={error} /> : null}</div></DocumentPanel></div><div className="space-y-4">{result ? <><DocumentPanel title="Résultat" icon="analytics"><div className="grid gap-5 p-4 sm:grid-cols-[auto_1fr]"><ScoreBadge value={result.analyse.score} /><p className="text-body leading-relaxed text-ink-muted">{result.analyse.recap}</p></div></DocumentPanel><DocumentPanel title="Recommandations" icon="tips_and_updates"><ul className="divide-y divide-line">{result.analyse.suggestions.map((s,i) => <li key={i} className="flex gap-3 px-4 py-3 text-body text-ink-muted"><span className="tabular text-accent">{i+1}</span>{s}</li>)}</ul></DocumentPanel><DocumentPanel title="Aperçu du CV lu" icon="visibility"><A4Preview cv={result.cv} /></DocumentPanel></> : <DocumentPanel title="Résultat de l’analyse" icon="analytics"><EmptyState icon="query_stats" title="Prêt à analyser" description="Le score ATS, les écarts et les recommandations apparaîtront ici." /></DocumentPanel>}</div></div></Screen>;
}

function Screen({ header, children }: { header: React.ReactNode; children: React.ReactNode }) { return <div className="flex h-full flex-col">{header}<div className="min-h-0 flex-1 overflow-y-auto p-5 min-[1200px]:p-6">{children}</div></div>; }
function Champ({ label, value, onChange }: { label:string; value:string; onChange:(v:string)=>void }) { return <FormField label={label}>{(props) => <TextInput {...props} value={value} onChange={(e) => onChange(e.target.value)} />}</FormField>; }
function message(error: unknown): string { return error instanceof AppError ? error.message : "Une erreur inattendue s’est produite."; }
function date(value: string): string { const d = new Date(value); return Number.isNaN(d.getTime()) ? value : new Intl.DateTimeFormat("fr-FR", { day:"2-digit", month:"short", year:"numeric" }).format(d); }
function isGeneration(value: unknown): value is GenerationCv { return typeof value === "object" && value !== null && "cv" in value && "analyse" in value; }

async function exporterPdf(
  cv: CvGenere,
  nom: string,
  notify: (toast: Omit<ToastMessage, "id">) => void,
) {
  const base = nom.trim().replace(/[\\/:*?"<>|]+/g, "-") || "cv-candilog";
  const chemin = await save({
    title: "Exporter le CV en PDF",
    defaultPath: `${base}.pdf`,
    filters: [{ name: "PDF", extensions: ["pdf"] }],
  });
  if (chemin === null) return;
  try {
    await documentsService.exporterPdf(cv, chemin);
    notify({ tone: "success", title: "CV exporté" });
  } catch (error) {
    notify({
      tone: "error",
      title: "Export PDF impossible",
      detail: error instanceof AppError ? error.message : undefined,
    });
  }
}
