import { useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import type { Profile } from "@/shared/types/generated/profile";
import { aiService, generation_id } from "@/features/ai/services/aiService";
import { useAiProgress } from "@/features/ai/viewmodel/useAiProgress";
import { AiProgress } from "@/features/documents/view/components/DocumentUi";
import { AppError } from "@/shared/types/app-error";
import { Button, ErrorBanner, Icon, ModalHost } from "@/shared/ui";

/** Import PDF avec aperçu explicite avant fusion dans le profil existant. */
export function ProfileImportModal({ open: visible, profile, busy, onClose, onSubmit }: { open: boolean; profile: Profile; busy: boolean; onClose: () => void; onSubmit: (profile: Profile) => Promise<unknown> }) {
  const [path, setPath] = useState<string | null>(null); const [operation, setOperation] = useState<string | null>(null); const [extracted, setExtracted] = useState<Profile | null>(null); const [error, setError] = useState<string | null>(null); const progress = useAiProgress(operation);
  const choisir = async () => { const file = await open({ multiple:false, filters:[{ name:"PDF", extensions:["pdf"] }] }); if (typeof file !== "string") return; setPath(file); setExtracted(null); setError(null); };
  const analyze = async () => { if (!path) return; const id = generation_id(); setOperation(id); setError(null); try { setExtracted((await aiService.importProfile({ generation_id:id, path:path })).profile); } catch(e) { if (!(e instanceof AppError && e.code === "CANCELLED")) setError(e instanceof AppError ? e.message : "Le CV n’a pas pu être analysé."); } finally { setOperation(null); } };
  const appliquer = async () => { if (!extracted) return; await onSubmit(fusionnerProfile(profile, extracted)); onClose(); };
  return <ModalHost open={visible} icon="upload_file" title="Importer depuis un CV" subtitle="L’IA prépare les données ; vous gardez le dernier mot" submitLabel="Ajouter au profil" submitIcon="playlist_add_check" submitDisabled={!extracted} busy={busy} onClose={onClose} onSubmit={() => void appliquer()} width="720px"><div className="space-y-4"><button type="button" onClick={() => void choisir()} className="flex w-full flex-col items-center gap-2 rounded-card border border-dashed border-accent-border bg-accent-tint px-6 py-7 text-center"><Icon name={path ? "picture_as_pdf" : "upload_file"} size={28} className="text-accent" /><span className="font-medium text-ink">{path ? path.split("/").at(-1) : "Choisir un CV PDF"}</span><span className="text-meta text-ink-muted">Lecture locale · 10 Mo maximum</span></button>{path && !extracted && !operation ? <Button variant="primary" icon="auto_awesome" className="w-full" onClick={() => void analyze()}>Analyser et préparer les données</Button> : null}{operation ? <><AiProgress progress={progress} /><Button variant="danger" icon="stop" className="w-full" onClick={() => void aiService.cancel(operation)}>Annuler l’analyse</Button></> : null}{error ? <ErrorBanner title="Import impossible" message={error} /> : null}{extracted ? <div className="rounded-card border border-line bg-surface-alt p-4"><div className="flex items-center gap-2"><Icon name="check_circle" size={18} className="text-success" /><p className="font-medium text-ink">Données prêtes à être ajoutées</p></div><p className="mt-2 text-body text-ink-muted">{[extracted.identity.first_name, extracted.identity.name].filter(Boolean).join(" ") || "Identité non détectée"}</p><dl className="mt-4 grid grid-cols-3 gap-3 text-center"><Count label="Expériences" value={extracted.experiences.length} /><Count label="Compétences" value={extracted.skills.length} /><Count label="Formations" value={extracted.education.length} /><Count label="Langues" value={extracted.languages.length} /><Count label="Projets" value={extracted.projects.length} /><Count label="Certifications" value={extracted.certifications.length} /></dl><p className="mt-4 text-meta leading-relaxed text-ink-faint">Les nouvelles entrées seront fusionnées avec votre profil. Les doublons exacts sont ignorés.</p></div> : null}</div></ModalHost>;
}

function Count({ label, value }: { label:string; value:number }) { return <div className="rounded-field bg-surface p-2"><dt className="text-[10px] text-ink-faint">{label}</dt><dd className="tabular mt-1 font-semibold text-ink">{value}</dd></div>; }

export function fusionnerProfile(current: Profile, imported: Profile): Profile {
  const text = (incoming: string | null, ancien: string | null) => incoming?.trim() ? incoming : ancien;
  const fusion = <T,>(a: T[], b: T[], key: (item:T) => string): T[] => { const vus = new Set(a.map((item) => key(item).trim().toLowerCase())); return [...a, ...b.filter((item) => { const k = key(item).trim().toLowerCase(); if (!k || vus.has(k)) return false; vus.add(k); return true; })]; };
  return { identity:{ first_name:text(imported.identity.first_name, current.identity.first_name) ?? "", name:text(imported.identity.name, current.identity.name) ?? "", email:text(imported.identity.email, current.identity.email) ?? "", phone:text(imported.identity.phone, current.identity.phone), city:text(imported.identity.city, current.identity.city), title:text(imported.identity.title, current.identity.title), resume:text(imported.identity.resume, current.identity.resume), linkedin:text(imported.identity.linkedin, current.identity.linkedin), github:text(imported.identity.github, current.identity.github), website:text(imported.identity.website, current.identity.website) }, experiences:fusion(current.experiences, imported.experiences, (v) => `${v.title}|${v.company}|${v.start_date}`), skills:fusion(current.skills, imported.skills, (v) => v.name), education:fusion(current.education, imported.education, (v) => `${v.degree}|${v.school}`), languages:fusion(current.languages, imported.languages, (v) => v.name), projects:fusion(current.projects, imported.projects, (v) => v.name), certifications:fusion(current.certifications, imported.certifications, (v) => v.name) };
}
