//! Helpers communs et déclaration des cas de test.
use super::*;

mod test_deserialise_analyse_ats_accepte_score_ats_en_chaine;
mod test_deserialise_analyse_ats_tolere_score_absent;
mod test_deserialise_cv_accepte_experiences_et_formations_en_chaines;
mod test_deserialise_cv_accepte_les_champs_absents;
mod test_deserialise_cv_tolere_un_objet_a_la_place_d_un_texte;
mod test_deserialise_experience_entier_est_toleree;
mod test_deserialise_skill_nombre_coerce_en_chaine;
